sudo: required
dist: trusty
language: java
jdk:
  - openjdk11

services:
  - rabbitmq
addons:
  apt:
    packages:
      - stompserver
env:
  - STOMPSERVER_PORT=63613

script:
  - sudo service stompserver stop
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo sed -i -e s/61613/$STOMPSERVER_PORT/ /etc/stompserver/stompserver.conf
  - sudo service stompserver start
  - export MONGO_URI=mongodb://127.0.0.1:27017/ninepanel
  - export SERVER_PORT=3000
  - ./gradlew ciTest
